### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by SteelSaint**
A more compact android index that has my notes as of 2/21/2017

### CODE REVIEW

**Comment by zwalters** [comment]
Looks good to me.

**Review by zwalters — APPROVED** [review]

**Review by DoctorWhoDat — APPROVED** [review]
Short and simple is the way to go, I like it

**Comment by ghost** [comment]
I liked how the original uses stack, but overall I think the changes are good.

**Comment by thomas-arnold-1** [comment]
good deal

**Pull request closed without merging**
